language: generic
dist: trusty
env:
  - EMACS_VERSION=25.1-travis
  - EMACS_VERSION=25.3-travis
  - EMACS_VERSION=26.1-travis
  - EMACS_VERSION=26.2-travis

install:
  - curl -fsSkL https://raw.githubusercontent.com/rejeep/evm/master/go | bash
  - export PATH="$HOME/.evm/bin:$PATH"
  - evm config path /tmp
  - evm install emacs-$EMACS_VERSION
  - export PATH="/tmp/emacs-$EMACS_VERSION/bin:$PATH"

script:
  - emacs -Q --batch -l package --eval '(push (cons "melpa" "http://melpa.org/packages/") package-archives)' -f package-initialize -f package-refresh-contents --eval "(package-install 'helm-core)"
  - emacs -Q --batch -f package-initialize -L . --eval "(setq byte-compile-error-on-warn t)" -f batch-byte-compile *.el
